name: 'Docker Build, Push and Update Repository'
description: 'Build Docker image, push to registry, and update another repository with new image tag'
author: 'GitHub Actions Workflows'

inputs:
  github-token:
    description: 'GitHub Personal Access Token with repo permissions'
    required: true
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '18'
  docker-registry:
    description: 'Docker registry URL'
    required: false
    default: 'persolive.azurecr.io'
  image-name:
    description: 'Docker ì´ë¯¸ì§€ ì´ë¦„ (ì˜ˆ: audio-engine-server)'
    required: true
  image-tag:
    description: 'Docker ì´ë¯¸ì§€ íƒœê·¸ (ì˜ˆ: v1.0.0, 2025.01.15.1430)'
    required: true
  dockerfile-path:
    description: 'Dockerfile ê²½ë¡œ'
    required: false
    default: './Dockerfile'
  build-context:
    description: 'ë¹Œë“œ ì»¨í…ìŠ¤íŠ¸'
    required: false
    default: '.'
  target-repo:
    description: 'ëŒ€ìƒ ë ˆí¬ì§€í† ë¦¬ (ì˜ˆ: owner/k8s-manifests)'
    required: true
  target-file-path:
    description: 'ì—…ë°ì´íŠ¸í•  íŒŒì¼ ê²½ë¡œ'
    required: true
  target-branch:
    description: 'ëŒ€ìƒ ë¸Œëžœì¹˜ (ë¯¸ì§€ì •ì‹œ ê¸°ë³¸ ë¸Œëžœì¹˜ ì‚¬ìš©)'
    required: false
    default: ''
  registry-username:
    description: 'Container Registry ì‚¬ìš©ìžëª…'
    required: false
  registry-password:
    description: 'Container Registry íŒ¨ìŠ¤ì›Œë“œ'
    required: false
  commit-message:
    description: 'ì»¤ë°‹ ë©”ì‹œì§€'
    required: false
    default: ''

outputs:
  image-tag:
    description: 'ìƒì„±ëœ ì´ë¯¸ì§€ íƒœê·¸'
    value: ${{ steps.docker-build-update.outputs.image-tag }}
  full-image-name:
    description: 'ì „ì²´ ì´ë¯¸ì§€ ì´ë¦„ (registry/image:tag)'
    value: ${{ steps.docker-build-update.outputs.full-image-name }}
  updated-file:
    description: 'ì—…ë°ì´íŠ¸ëœ íŒŒì¼ ê²½ë¡œ'
    value: ${{ steps.docker-build-update.outputs.updated-file }}
  commit-message:
    description: 'ì»¤ë°‹ ë©”ì‹œì§€'
    value: ${{ steps.docker-build-update.outputs.commit-message }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Download docker build update script
      shell: bash
      run: |
        echo "ðŸ“¥ Downloading Docker build and update script..."
        curl -fsSL -o /tmp/docker-build-push-update.js https://raw.githubusercontent.com/akfmdl/github-actions-workflows/test/scripts/docker-build-push-update.js
        chmod +x /tmp/docker-build-push-update.js
        
    - name: Docker build, push and update repository
      id: docker-build-update
      shell: bash
      env:
        DOCKER_REGISTRY: ${{ inputs.docker-registry }}
        IMAGE_NAME: ${{ inputs.image-name }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        DOCKERFILE_PATH: ${{ inputs.dockerfile-path }}
        BUILD_CONTEXT: ${{ inputs.build-context }}
        TARGET_REPO: ${{ inputs.target-repo }}
        TARGET_FILE_PATH: ${{ inputs.target-file-path }}
        TARGET_BRANCH: ${{ inputs.target-branch }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REGISTRY_USERNAME: ${{ inputs.registry-username }}
        REGISTRY_PASSWORD: ${{ inputs.registry-password }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        SOURCE_REPOSITORY: ${{ github.repository }}
      run: |
        echo "ðŸš€ Docker ì´ë¯¸ì§€ ë¹Œë“œ ë° ë ˆí¬ì§€í† ë¦¬ ì—…ë°ì´íŠ¸ë¥¼ ì‹œìž‘í•©ë‹ˆë‹¤..."
        node /tmp/docker-build-push-update.js
        
    - name: Summary
      shell: bash
      run: |
        echo "## ðŸŽ‰ Docker Build & Update ì™„ë£Œ!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Docker ì´ë¯¸ì§€ ì •ë³´" >> $GITHUB_STEP_SUMMARY
        echo "- **Registry**: ${{ inputs.docker-registry }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Image**: ${{ inputs.image-name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Tag**: ${{ steps.docker-build-update.outputs.image-tag }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Full Name**: ${{ steps.docker-build-update.outputs.full-image-name }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ì—…ë°ì´íŠ¸ ëŒ€ìƒ" >> $GITHUB_STEP_SUMMARY
        echo "- **Repository**: ${{ inputs.target-repo }}" >> $GITHUB_STEP_SUMMARY
        echo "- **File**: ${{ inputs.target-file-path }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ì—…ë°ì´íŠ¸ ê²°ê³¼" >> $GITHUB_STEP_SUMMARY
        echo "- **ì—…ë°ì´íŠ¸ëœ íŒŒì¼**: ${{ steps.docker-build-update.outputs.updated-file }}" >> $GITHUB_STEP_SUMMARY
        echo "- **ì»¤ë°‹ ë©”ì‹œì§€**: ${{ steps.docker-build-update.outputs.commit-message }}" >> $GITHUB_STEP_SUMMARY

branding:
  icon: 'package'
  color: 'blue' 