name: 'Update Repository File and Create PR'
description: 'Update a file in another repository and create a pull request automatically'
author: 'GitHub Actions Workflows'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  ssh-key:
    description: 'SSH key for authentication'
    required: false
    default: ''
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '18'
  working-directory:
    description: 'Working directory for the action'
    required: false
    default: '.'
  target-repo:
    description: 'ëŒ€ìƒ ë ˆí¬ì§€í† ë¦¬ (ì˜ˆ: owner/repo-name)'
    required: true
  file-path:
    description: 'ìˆ˜ì •í•  íŒŒì¼ ê²½ë¡œ'
    required: true
  variable-name:
    description: 'ìˆ˜ì •í•  ë³€ìˆ˜ëª…'
    required: true
  new-value:
    description: 'ìƒˆë¡œìš´ ê°’'
    required: true
  commit-message:
    description: 'ì»¤ë°‹ ë©”ì‹œì§€ (ê¸°ë³¸ê°’: Update {variable-name} to {new-value})'
    required: false
    default: ''
  pr-title:
    description: 'Pull Request ì œëª© (ê¸°ë³¸ê°’: Update {variable-name} in {file_path})'
    required: false
    default: ''
  pr-body:
    description: 'Pull Request ë³¸ë¬¸ (ê¸°ë³¸ê°’: ìžë™ ìƒì„±)'
    required: false
    default: ''

outputs:
  pr-url:
    description: 'ìƒì„±ëœ Pull Request URL'
    value: ${{ steps.update-repo.outputs.pr-url }}
  pr-number:
    description: 'ìƒì„±ëœ Pull Request ë²ˆí˜¸'
    value: ${{ steps.update-repo.outputs.pr-number }}
  branch-name:
    description: 'ìƒì„±ëœ ë¸Œëžœì¹˜ ì´ë¦„'
    value: ${{ steps.update-repo.outputs.branch-name }}

runs:
  using: 'composite'
  steps:
    - name: Checkout ì½”ë“œ
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ssh-key: ${{ inputs.ssh-key }}
        token: ${{ inputs.github-token }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f "package.json" ]; then
          echo "ðŸ“¦ Installing project dependencies..."
          if [ -f "package-lock.json" ]; then
            npm ci
          elif [ -f "yarn.lock" ]; then
            yarn install --frozen-lockfile
          elif [ -f "pnpm-lock.yaml" ]; then
            npm install -g pnpm
            pnpm install --frozen-lockfile
          else
            npm install
          fi
          
          # @octokit/restê°€ package.jsonì— ì—†ë‹¤ë©´ ì¶”ê°€ë¡œ ì„¤ì¹˜
          if ! npm list @octokit/rest >/dev/null 2>&1; then
            echo "ðŸ“¦ Installing @octokit/rest..."
            npm install @octokit/rest
          else
            echo "âœ… @octokit/rest already installed"
          fi
        else
          echo "ðŸ“¦ No package.json found, installing required dependencies only..."
          npm install @octokit/rest
        fi
        
    - name: Download update script
      shell: bash
      run: |
        echo "ðŸ“¥ Downloading update repository script..."
        curl -fsSL -o /tmp/update-repo.js https://raw.githubusercontent.com/akfmdl/github-actions-workflows/test/scripts/update-repo.js
        chmod +x /tmp/update-repo.js
        
    - name: Update repository file and create PR
      id: update-repo
      shell: bash
      env:
        TARGET_REPO: ${{ inputs.target-repo }}
        FILE_PATH: ${{ inputs.file-path }}
        VARIABLE_NAME: ${{ inputs.variable-name }}
        NEW_VALUE: ${{ inputs.new-value }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        PR_TITLE: ${{ inputs.pr-title }}
        PR_BODY: ${{ inputs.pr_body }}
        SOURCE_REPOSITORY: ${{ github.repository }}
        SOURCE_WORKFLOW: ${{ github.workflow }}
        SOURCE_RUN_ID: ${{ github.run_id }}
      run: |
        echo "ðŸš€ ë ˆí¬ì§€í† ë¦¬ ì—…ë°ì´íŠ¸ ë° PR ìƒì„±ì„ ì‹œìž‘í•©ë‹ˆë‹¤..."
        node /tmp/update-repo.js
        
    - name: Summary
      shell: bash
      run: |
        echo "## ðŸŽ‰ ìž‘ì—… ì™„ë£Œ!" >> $GITHUB_STEP_SUMMARY
        echo "- **ëŒ€ìƒ ë ˆí¬ì§€í† ë¦¬:** ${{ inputs.target-repo }}" >> $GITHUB_STEP_SUMMARY
        echo "- **ìˆ˜ì •ëœ íŒŒì¼:** ${{ inputs.file-path }}" >> $GITHUB_STEP_SUMMARY
        echo "- **ë³€ìˆ˜ëª…:** ${{ inputs.variable-name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **ìƒˆ ê°’:** ${{ inputs.new-value }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -n "${{ steps.update-repo.outputs.pr-url }}" ]; then
          echo "âœ… **Pull Requestê°€ ì„±ê³µì ìœ¼ë¡œ ìƒì„±ë˜ì—ˆìŠµë‹ˆë‹¤!**" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ”— **PR URL:** ${{ steps.update-repo.outputs.pr-url }}" >> $GITHUB_STEP_SUMMARY
        fi

branding:
  icon: 'git-pull-request'
  color: 'green' 