name: 'Update Repository File and Create PR'
description: 'Update a file in another repository and create a pull request automatically using GitHub Personal Access Token'
author: 'GitHub Actions Workflows'

inputs:
  github-token:
    description: 'GitHub Personal Access Token with repo permissions'
    required: true
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '18'
  working-directory:
    description: 'Working directory for the action'
    required: false
    default: '.'
  target-repo:
    description: 'ëŒ€ìƒ ë ˆí¬ì§€í† ë¦¬ (ì˜ˆ: owner/repo-name)'
    required: true
  file-path:
    description: 'ìˆ˜ì •í•  íŒŒì¼ ê²½ë¡œ'
    required: true
  variable-name:
    description: 'ìˆ˜ì •í•  ë³€ìˆ˜ëª…'
    required: true
  new-value:
    description: 'ìƒˆë¡œìš´ ê°’'
    required: true
  commit-message:
    description: 'ì»¤ë°‹ ë©”ì‹œì§€ (ê¸°ë³¸ê°’: Update {variable-name} to {new-value})'
    required: false
    default: ''
  pr-title:
    description: 'Pull Request ì œëª© (ê¸°ë³¸ê°’: Update {variable-name} in {file_path})'
    required: false
    default: ''
  pr-body:
    description: 'Pull Request ë³¸ë¬¸ (ê¸°ë³¸ê°’: ìžë™ ìƒì„±)'
    required: false
    default: ''
  release-version:
    description: 'í˜„ìž¬ ë ˆí¬ì§€í† ë¦¬ì˜ ë¦´ë¦¬ì¦ˆ ë²„ì „ (ì„ íƒì‚¬í•­)'
    required: false
    default: ''

outputs:
  pr-url:
    description: 'ìƒì„±ëœ Pull Request URL'
    value: ${{ steps.update-repo.outputs.pr-url }}
  pr-number:
    description: 'ìƒì„±ëœ Pull Request ë²ˆí˜¸'
    value: ${{ steps.update-repo.outputs.pr-number }}
  branch-name:
    description: 'ìƒì„±ëœ ë¸Œëžœì¹˜ ì´ë¦„'
    value: ${{ steps.update-repo.outputs.branch-name }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Download update script
      shell: bash
      run: |
        echo "ðŸ“¥ Downloading update repository script..."
        curl -fsSL -o /tmp/update-repo-pat-token.js https://raw.githubusercontent.com/akfmdl/github-actions-workflows/test/scripts/update-repo-pat-token.js
        chmod +x /tmp/update-repo-pat-token.js
        
    - name: Update repository file and create PR
      id: update-repo
      shell: bash
      env:
        TARGET_REPO: ${{ inputs.target-repo }}
        FILE_PATH: ${{ inputs.file-path }}
        VARIABLE_NAME: ${{ inputs.variable-name }}
        NEW_VALUE: ${{ inputs.new-value }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        PR_TITLE: ${{ inputs.pr-title }}
        PR_BODY: ${{ inputs.pr-body }}
        SOURCE_REPOSITORY: ${{ github.repository }}
        SOURCE_WORKFLOW: ${{ github.workflow }}
        SOURCE_RUN_ID: ${{ github.run_id }}
        RELEASE_VERSION: ${{ inputs.release-version }}
      run: |
        echo "ðŸš€ ë ˆí¬ì§€í† ë¦¬ ì—…ë°ì´íŠ¸ ë° PR ìƒì„±ì„ ì‹œìž‘í•©ë‹ˆë‹¤..."
        node /tmp/update-repo-pat-token.js
        
    - name: Summary
      shell: bash
      run: |
        echo "## ðŸŽ‰ ìž‘ì—… ì™„ë£Œ!" >> $GITHUB_STEP_SUMMARY
        echo "- **ëŒ€ìƒ ë ˆí¬ì§€í† ë¦¬:** ${{ inputs.target-repo }}" >> $GITHUB_STEP_SUMMARY
        echo "- **ìˆ˜ì •ëœ íŒŒì¼:** ${{ inputs.file-path }}" >> $GITHUB_STEP_SUMMARY
        echo "- **ë³€ìˆ˜ëª…:** ${{ inputs.variable-name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **ìƒˆ ê°’:** ${{ inputs.new-value }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "âœ… **íŒŒì¼ ìˆ˜ì • ë° Pull Request ìƒì„± ì™„ë£Œ!**" >> $GITHUB_STEP_SUMMARY
        echo "ðŸ”— **PR URL:** ${{ steps.update-repo.outputs.pr-url }}" >> $GITHUB_STEP_SUMMARY
        echo "ðŸ”¢ **PR ë²ˆí˜¸:** ${{ steps.update-repo.outputs.pr-number }}" >> $GITHUB_STEP_SUMMARY
        echo "ðŸŒ¿ **ë¸Œëžœì¹˜:** ${{ steps.update-repo.outputs.branch-name }}" >> $GITHUB_STEP_SUMMARY

branding:
  icon: 'git-pull-request'
  color: 'green' 